### ISSUE TITLE
Kartın IO larını gpiozero İle Kontrol Edebilirmiyim? 

### ISSUE THREAD

**Issue by fahrettine** [pe2a/MedIOEx#1]
Kartın IO larını gpiozero İle Kontrol Edebilirmiyim? Can I control IO by gpiozero module?

**Comment by pe2a** [comment]
Evet, kontrol edebilirsiniz. Dikkat edilmesi gereken birkaç nokta var. Kullanacağınız SD kartı sadece Raspberry Pi Zero'da çalıştırmanızı öneriyoruz. Yani Raspberry Pi 3/4'de programı derleyip Raspberry Pi Zero üzerinde çalıştırmanız yazılım-donanım uyumsuzluğuna neden olabilir. Bu duruma özellikle seri port ile ilgili işlemlerde rastlıyoruz.
